export const DISPLAY_VIEW_MODAL_ID = 'displayView-modal-container'
export const SEARCH_MODAL_ID = 'search-modal-container'
export const LANGUAGE_CHANGER_MODAL_ID = 'languageChanger-modal-container'
export const PARAMETER_MODAL_ID = 'parameter-modal-container'
export const COLOR_MODAL_ID = 'color-modal-container'
