enum Enum {

    IMAGE_IN_SMB,
    IMAGE_IN_SMB3,
    IMAGE_IN_SMW,
    IMAGE_IN_NSMBU,
    IMAGE_IN_SM3DW,
    IMAGES_ON_EDITOR,
    IMAGES_ON_CLEAR_CONDITION,
    IMAGES_ON_WHILE_PLAYING,
    IMAGES_ON_UNUSED,

    NAME,

    GAME,
    WHEN_ALL_SELECTED_GAME,

    GAME_STYLE,
    WHEN_ALL_SELECTED_GAME_STYLE,

    COURSE_THEME,
    WHEN_ALL_SELECTED_COURSE_THEME,

    TIME,
    WHEN_ALL_SELECTED_TIME,

    CATEGORY,
    CATEGORY_AS_TEXT,

    EDITOR_LIMIT_IN_SMM1_AND_3DS,
    EDITOR_LIMIT_IN_SMM1_AND_3DS_ONLY,
    EDITOR_LIMIT_IN_SMM2,
    EDITOR_LIMIT_IN_SMM2_ONLY,
    PLAY_LIMIT,

}

export type Ordinals = typeof Enum[Names]
export type Names = keyof typeof Enum
