enum Enum {

    IMAGES,
    IMAGES_ON_EDITOR,
    IMAGES_ON_CLEAR_CONDITION,
    IMAGES_ON_WHILE_PLAYING,
    IMAGES_ON_UNUSED,

    NAME,

    GAME,
    WHEN_ALL_SELECTED_GAME,

    GAME_STYLE,
    WHEN_ALL_SELECTED_GAME_STYLE,

    COURSE_THEME,
    WHEN_ALL_SELECTED_COURSE_THEME,

    TIME,
    WHEN_ALL_SELECTED_TIME,

    CATEGORY,
    CATEGORY_AS_TEXT,

    LIMIT,
    LIMIT_IN_SMM1_AND_3DS,
    LIMIT_IN_SMM2,

}

export type Ordinals = typeof Enum[Names]
export type Names = keyof typeof Enum
